// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSConstantsiOS
{
        public const string achievement_sextillionaire = "CgkI1rDm6sMKEAIQCg"; // <GPGSID>
        public const string achievement_undecillionaire = "CgkI1rDm6sMKEAIQEg"; // <GPGSID>
        public const string achievement_decillionaire = "CgkI1rDm6sMKEAIQEQ"; // <GPGSID>
        public const string achievement_sandwich_chef = "CgkI1rDm6sMKEAIQCQ"; // <GPGSID>
        public const string achievement_quintillionaire = "CgkI1rDm6sMKEAIQCA"; // <GPGSID>
        public const string achievement_quattuordecillionaire = "CgkI1rDm6sMKEAIQFQ"; // <GPGSID>
        public const string achievement_octillionaire = "CgkI1rDm6sMKEAIQDw"; // <GPGSID>
        public const string leaderboard_total_elixirs_earned = "CgkI1rDm6sMKEAIQDg"; // <GPGSID>
        public const string achievement_sexdecillionaire = "CgkI1rDm6sMKEAIQFw"; // <GPGSID>
        public const string achievement_new_world_order = "CgkI1rDm6sMKEAIQAQ"; // <GPGSID>
        public const string achievement_time_traveler = "CgkI1rDm6sMKEAIQAg"; // <GPGSID>
        public const string achievement_quadrillionaire = "CgkI1rDm6sMKEAIQBg"; // <GPGSID>
        public const string achievement_all_hail = "CgkI1rDm6sMKEAIQAw"; // <GPGSID>
        public const string achievement_i_declare_war = "CgkI1rDm6sMKEAIQGA"; // <GPGSID>
        public const string leaderboard_total_money_made = "CgkI1rDm6sMKEAIQDQ"; // <GPGSID>
        public const string achievement_duodecillionaire = "CgkI1rDm6sMKEAIQEw"; // <GPGSID>
        public const string achievement_tredecillionaire = "CgkI1rDm6sMKEAIQFA"; // <GPGSID>
        public const string achievement_millionaire = "CgkI1rDm6sMKEAIQBA"; // <GPGSID>
        public const string achievement_trillionaire = "CgkI1rDm6sMKEAIQBw"; // <GPGSID>
        public const string achievement_billionaire = "CgkI1rDm6sMKEAIQBQ"; // <GPGSID>
        public const string leaderboard_swipes = "CgkI1rDm6sMKEAIQDA"; // <GPGSID>
        public const string achievement_septillionaire = "CgkI1rDm6sMKEAIQCw"; // <GPGSID>
        public const string achievement_quindecillionaire = "CgkI1rDm6sMKEAIQFg"; // <GPGSID>
        public const string achievement_nonillionaire = "CgkI1rDm6sMKEAIQEA"; // <GPGSID>

}

